# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.3
#         with:
#           projectBaseDir: /home/runner/_work/SS3D-browser-electron/SS3D-browser-electron/
#           sources: ./src/*
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: /home/runner/_work/SS3D-browser-electron/SS3D-browser-electron/ sonar-scanner
#   build:
#     # The type of runner that the job will run on
#     runs-on: self-hosted

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Build
#       run: yarn electron:windows

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: echo 
